import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import JsonLd from '../components/JsonLd';
import { SITE } from '../lib/seo';

export const metadata: Metadata = {
  title: 'How It Works — Generate a Turnitin Report in 3 Steps',
  description:
    'Learn exactly how our free Turnitin report generator works. Upload your PDF, choose custom AI and similarity percentages, and download an authentic Turnitin-style report in under 10 seconds.',
  keywords: [
    'how to generate turnitin report',
    'turnitin report generator how it works',
    'create turnitin report online',
    'turnitin report steps',
  ],
  alternates: { canonical: '/how-it-works' },
  openGraph: {
    title: 'How It Works — Generate a Turnitin Report in 3 Steps',
    description:
      'Upload PDF, choose AI and similarity percentages, download authentic Turnitin-style PDF in seconds.',
    url: `${SITE.url}/how-it-works`,
    type: 'article',
  },
};

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a Turnitin Report Online',
  description:
    'Step-by-step guide to generating a free, custom Turnitin similarity and AI detection report.',
  totalTime: 'PT10S',
  estimatedCost: { '@type': 'MonetaryAmount', currency: 'USD', value: '0' },
  step: [
    {
      '@type': 'HowToStep',
      name: 'Upload your PDF',
      text: 'Drag and drop your PDF document (up to 10MB) into the upload area on the home page.',
      url: `${SITE.url}/#generator`,
    },
    {
      '@type': 'HowToStep',
      name: 'Set custom percentages',
      text: 'Pick any AI detection percentage and similarity percentage between 0% and 100%.',
    },
    {
      '@type': 'HowToStep',
      name: 'Download your report',
      text: 'Receive two PDFs — an AI Detection Report and a Similarity Report — ready to download in seconds.',
    },
  ],
};

const breadcrumbSchema = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: SITE.url },
    { '@type': 'ListItem', position: 2, name: 'How It Works', item: `${SITE.url}/how-it-works` },
  ],
};

export default function HowItWorksPage() {
  return (
    <>
      <JsonLd data={[howToSchema, breadcrumbSchema]} />
      <SiteHeader />

      <section className="page-header">
        <div className="container">
          <nav className="breadcrumbs" aria-label="Breadcrumb">
            <Link href="/">Home</Link> <span>/</span> <span>How It Works</span>
          </nav>
          <h1 className="section-title">
            How the <span className="grad">Turnitin Report Generator</span> works
          </h1>
          <p className="section-subtitle" style={{ margin: '0.75rem auto 0' }}>
            Three simple steps. No signup, no payment, no waiting. Generate authentic Turnitin similarity and AI detection reports in under 10 seconds.
          </p>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <div className="steps-grid">
            <div className="step-card">
              <div className="step-num">01</div>
              <h3 className="step-title">Upload your PDF document</h3>
              <p className="step-desc">
                Drag and drop your PDF — up to 10MB — onto the upload area or click to browse.
                Your file stays in your browser; nothing is uploaded to a server.
              </p>
            </div>
            <div className="step-card">
              <div className="step-num">02</div>
              <h3 className="step-title">Set custom percentages</h3>
              <p className="step-desc">
                Pick any AI detection percentage (0–100%) and any similarity
                percentage (0–100%) to perfectly tailor the report you need.
              </p>
            </div>
            <div className="step-card">
              <div className="step-num">03</div>
              <h3 className="step-title">Download your PDFs</h3>
              <p className="step-desc">
                Get two Turnitin-style PDFs — AI Detection Report and Similarity
                Report — ready to download in seconds.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="section">
        <div className="container">
          <article className="prose">
            <h2>What you get with every generation</h2>
            <p>
              Each Turnitin report generated by our tool includes a complete,
              authentic-looking PDF with all the visual elements students and
              educators are familiar with: color-coded similarity highlights,
              originality score summary, document metadata, word and character
              counts, page totals, file size, and footer details.
            </p>

            <h2>Why a custom Turnitin report?</h2>
            <p>
              A <Link href="/custom-turnitin-report">custom Turnitin report</Link> lets you control
              exactly what percentage the final PDF shows. This is useful for previewing
              what your essay or article would score, demonstrating how the Turnitin
              system flags content, or simply producing a clean similarity report for
              client deliverables.
            </p>

            <h2>Is this safe?</h2>
            <p>
              Yes. Document processing runs entirely client-side in your browser
              using <code>pdf-lib</code>, <code>pdfjs-dist</code>, and <code>react-pdf</code>.
              We never see, store, or transmit your files. Read more in our{' '}
              <Link href="/privacy-policy">Privacy Policy</Link>.
            </p>

            <h2>Ready to try it?</h2>
            <p>
              Head to the <Link href="/">free Turnitin report generator</Link> and
              create your first report in seconds.
            </p>
          </article>
        </div>
      </section>

      <SiteFooter />
    </>
  );
}
